// Isolated browser verification; never point SCHOLARTRAIL_TEST_DIR at a personal profile.
import { createRequire } from 'node:module';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { blankDB, createProject, changeProject, recordClick, editRecord, setPaperTag } from '../extension/lib/core.js';
import { createBackup } from '../extension/lib/backup.js';
const require = createRequire(import.meta.url), { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.resolve(process.env.SCHOLARTRAIL_TEST_DIR || path.join(root, 'test-results/backup'));
await mkdir(out, { recursive: true });
const extension = path.join(root, 'extension'), checks = [], errors = [];
const pass = name => { checks.push(name); console.log(`PASS ${name}`); };
const options = { channel: 'chromium', headless: true, args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`], viewport: { width: 1440, height: 1050 } };
let context = await chromium.launchPersistentContext(path.join(out, 'profile'), options);
try {
  let worker = context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
  await worker.evaluate(() => chrome.storage.local.clear());
  const id = new URL(worker.url()).host, app = await context.newPage();
  app.on('pageerror', e => errors.push(e.message));
  const api = async (type, fields = {}) => { const result = await app.evaluate(m => chrome.runtime.sendMessage(m), { type, ...fields }); assert.equal(result.ok, true, result.error); return result.data; };
  const source = blankDB(), project = createProject(source, '文献综述'), archived = createProject(source, '研究专题');
  const { paper } = recordClick(source, { title: 'A practical guide to literature review methods', authors: 'R Taylor', year: '2018', primary_url: 'https://example.org/review', external_ids: ['scholar:cid:review2018'] }, project.id, { search_query: 'literature review methods', source_url: 'https://scholar.google.com/scholar?q=literature+review+methods' });
  editRecord(source, project.id, paper.id, { note: '可用于方法部分。\n下次比较研究设计。', not_relevant: true });
  setPaperTag(source, project.id, { paper_id: paper.id, name: '待精读', color: 'green' });
  recordClick(source, paper, archived.id); editRecord(source, archived.id, paper.id, { note: '另一个项目的独立笔记。' });
  changeProject(source, 'archive', archived.id); changeProject(source, 'switch', project.id);
  const backup = createBackup(source), text = JSON.stringify(backup);
  const file = (content = text, name = 'scholartrail-backup.json') => ({ name, mimeType: 'application/json', buffer: Buffer.from(content) });
  const select = async (content = text) => { await app.locator('#backup-file').setInputFiles(file(content)); };
  await app.goto(`chrome-extension://${id}/app.html`);
  await app.getByRole('button', { name: '已有备份？导入研究数据' }).waitFor();
  const chooser = app.waitForEvent('filechooser'); await app.locator('#welcome-import').click(); await (await chooser).setFiles(file());
  await app.locator('#import-dialog[open]').waitFor();
  assert.match(await app.locator('#import-summary').textContent(), /2 个项目、2 条论文记录、2 条笔记、1 个标签和 2 条点击历史/);
  assert.equal((await api('GET_STATE')).projects.length, 0);
  await app.screenshot({ path: path.join(out, 'import-preview.png'), fullPage: true });
  await app.locator('#cancel-import').click(); assert.equal((await api('GET_STATE')).projects.length, 0);
  pass('Onboarding file selection previews a backup; cancel leaves the empty installation untouched');
  await select(); await app.locator('#confirm-import').click(); await app.locator('.paper-card').waitFor();
  let state = await api('GET_STATE');
  assert.equal(state.projects.length, 2); assert.equal(state.projects.find(p => p.id === archived.id).archived_at, source.projects[1].archived_at);
  assert.equal(state.active_project_id, project.id); assert.equal(state.project_papers[0].note, source.project_papers[0].note); assert.equal(state.tags[0].name, '待精读');
  assert.equal((await api('GET_HISTORY', { project_id: project.id, paper_id: paper.id })).length, 1);
  await app.locator('.paper-card.excluded').waitFor();
  await context.route('https://scholar.google.com/**', async r => r.fulfill({ contentType: 'text/html', body: await readFile(path.join(root, 'tests/scholar-fixture.html'), 'utf8') }));
  const scholar = await context.newPage(); await scholar.goto('https://scholar.google.com/scholar?q=literature+review+methods');
  await scholar.locator('.scholartrail-excluded').waitFor(); await scholar.getByText('✓ 之前点过', { exact: true }).waitFor(); await scholar.getByRole('button', { name: '▤ 笔记', exact: true }).waitFor();
  pass('Confirmed restore recovers archive status, notes, tags, exclusion and click history on the actual Scholar UI');
  await app.goto(`chrome-extension://${id}/app.html#settings`);
  await app.locator('#export-data').waitFor();
  const download = app.waitForEvent('download'); await app.locator('#export-data').click();
  const exported = await download; await exported.saveAs(path.join(out, 'exported.json'));
  const exportedData = JSON.parse(await readFile(path.join(out, 'exported.json'), 'utf8'));
  assert.equal(exportedData.projects.length, 2); assert.equal(exportedData.project_papers[0].note, source.project_papers[0].note);
  const beforeDownload = app.waitForEvent('download'); await app.locator('#export-before-import').click();
  await (await beforeDownload).saveAs(path.join(out, 'before-import.json'));
  assert.equal(JSON.parse(await readFile(path.join(out, 'before-import.json'), 'utf8')).projects.length, 0);
  pass('Export and the automatic before-import backup both download valid JSON through the interface');
  await select(); await app.locator('#import-dialog[open]').waitFor();
  assert.equal(await app.locator('#confirm-import').isDisabled(), true); assert.match(await app.locator('#import-details').textContent(), /2 个项目.*跳过/);
  await app.locator('#cancel-import').click(); assert.equal((await api('GET_STATE')).projects.length, 2);
  pass('Importing the same backup again is visibly skipped without duplicate projects');
  const invalidState = await api('EXPORT'); await select('{ invalid JSON'); await app.getByText(/不是有效的 JSON/).waitFor();
  assert.equal(await app.locator('#import-dialog').isVisible(), false); const afterInvalid = await api('EXPORT'); delete invalidState.exported_at; delete afterInvalid.exported_at; assert.deepEqual(afterInvalid, invalidState);
  pass('Invalid JSON shows a readable error and leaves all existing research unchanged');
  const changed = structuredClone(backup); changed.project_papers[0].note = '备份中不同的一条笔记。';
  await select(JSON.stringify(changed)); await app.locator('#import-dialog[open]').waitFor();
  assert.match(await app.locator('#import-details').textContent(), /1 个同名项目/);
  await api('EDIT_RECORD', { project_id: project.id, paper_id: paper.id, patch: { note: '预览期间新增的本地笔记。' } });
  await app.locator('#confirm-import').click(); await app.locator('#import-error').getByText('当前数据已更新，预览已刷新，请再次确认。').waitFor();
  assert.equal((await api('GET_STATE')).projects.length, 2); await app.locator('#confirm-import').click();
  await app.getByText(/导入完成：添加 1 个项目/).waitFor();
  state = await api('GET_STATE'); const copy = state.projects.find(p => p.name === '文献综述（导入）'); assert.ok(copy);
  assert.equal(state.project_papers.find(r => r.project_id === project.id).note, '预览期间新增的本地笔记。'); assert.equal(state.project_papers.find(r => r.project_id === copy.id).note, changed.project_papers[0].note);
  pass('Concurrent local edits require a fresh confirmation; conflicting notes are kept in independent project copies');
  assert.deepEqual(errors, []); await context.close(); context = await chromium.launchPersistentContext(path.join(out, 'profile'), options);
  const reopened = await context.newPage(); await reopened.goto(`chrome-extension://${id}/app.html#settings`);
  const persisted = await reopened.evaluate(() => chrome.runtime.sendMessage({ type: 'GET_STATE' }));
  assert.equal(persisted.data.projects.length, 3); assert.equal(persisted.data.import_backup_available, true); await reopened.locator('#export-before-import:not([disabled])').waitFor();
  pass('Imported projects and the before-import backup survive a full browser restart without page errors');
  await writeFile(path.join(out, 'results.json'), JSON.stringify({ checks, errors, fixture: 'Real isolated Chromium extension with synthetic backups and representative Scholar DOM' }, null, 2));
} finally { await context.close(); }
