// Run with Playwright installed: node tests/e2e.mjs
// Optional: PLAYWRIGHT_MODULE, PLAYWRIGHT_BROWSERS_PATH, SCHOLARTRAIL_TEST_DIR.
import { createRequire } from 'node:module';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.resolve(process.env.SCHOLARTRAIL_TEST_DIR || path.join(root,'test-results'));
await mkdir(out,{recursive:true});
const extension=path.join(root,'extension'), errors=[], checks=[];
const pass=name=>{checks.push(name);console.log(`PASS ${name}`);};
const options={channel:'chromium',headless:true,args:[`--disable-extensions-except=${extension}`,`--load-extension=${extension}`],viewport:{width:1440,height:1050}};
let context=await chromium.launchPersistentContext(path.join(out,'profile'),options);
try {
  let worker=context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
  await worker.evaluate(()=>chrome.storage.local.clear());
  const id=new URL(worker.url()).host, app=await context.newPage();
  context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
  app.on('pageerror',e=>errors.push(e.message));
  const api=async(type,fields={})=>{const r=await app.evaluate(m=>chrome.runtime.sendMessage(m),{type,...fields});assert.equal(r.ok,true,r.error);return r.data;};
  await app.goto(`chrome-extension://${id}/app.html`);
  await app.getByRole('textbox',{name:'项目名称',exact:true}).fill('文献综述');
  await app.locator('#welcome-form button').click();
  await app.waitForSelector('#paper-list');
  let state=await api('GET_STATE'), projectA=state.active_project_id;
  assert.equal(state.projects.length,1);pass('Onboarding creates a real project with an empty library');
  const fixture=await readFile(path.join(root,'tests/scholar-fixture.html'),'utf8');
  await context.route('https://scholar.google.com/**',r=>r.fulfill({contentType:'text/html',body:fixture}));
  await context.route('https://example.org/**',r=>r.fulfill({contentType:'text/html',body:'<h1>Research paper destination</h1>'}));
  const scholar=await context.newPage();
  await scholar.goto('https://scholar.google.com/scholar?q=literature+review+methods');
  await scholar.getByRole('button',{name:/ScholarTrail · 文献综述/}).waitFor();
  assert.equal((await api('GET_STATE')).papers.length,0);assert.equal(await scholar.getByText('✓ 之前点过',{exact:true}).count(),0);pass('Simply appearing in Scholar records no seen/clicked history');
  await scholar.locator('.gs_rt a').first().click();
  await scholar.waitForURL('https://example.org/review');
  await scholar.goBack();
  await scholar.getByText('✓ 之前点过',{exact:true}).waitFor();
  state=await api('GET_STATE');assert.equal(state.papers.length,1);const first=state.papers[0];
  const history=await api('GET_HISTORY',{project_id:projectA,paper_id:first.id});assert.equal(history[0].search_query,'literature review methods');pass('Native same-tab navigation saves click + query + time before leaving');
  await scholar.getByRole('button',{name:'+ 添加笔记',exact:true}).click();
  await scholar.getByRole('textbox',{name:'文献综述的笔记'}).fill('可用于文献综述的方法部分，之后再比较研究设计。');
  await scholar.getByRole('button',{name:'保存笔记',exact:true}).click();
  await scholar.getByRole('button',{name:'▤ 笔记',exact:true}).waitFor();
  await scholar.getByRole('button',{name:'× 不相关',exact:true}).click();
  await scholar.locator('.scholartrail-excluded').waitFor();
  await scholar.reload();await scholar.locator('.scholartrail-excluded').waitFor();
  await scholar.getByRole('button',{name:'撤销',exact:true}).click();
  await scholar.waitForFunction(()=>!document.querySelector('.scholartrail-excluded'));
  assert.match((await api('GET_STATE')).project_papers[0].note,/方法部分/);pass('Inline notes, exclusion, refresh recognition and Undo preserve history');
  const projectB=await api('CREATE_PROJECT',{name:'研究专题'});
  await scholar.getByRole('button',{name:/ScholarTrail · 研究专题/}).waitFor();
  assert.equal(await scholar.getByText('✓ 之前点过',{exact:true}).count(),0);pass('Project switching clears inherited click, note and exclusion states');
  await api('PROJECT_ACTION',{action:'switch',project_id:projectA});
  await scholar.getByRole('button',{name:/ScholarTrail · 文献综述/}).waitFor();
  for(const nth of [1,2]) { const popup=context.waitForEvent('page');await scholar.locator('.gs_rt a').nth(nth).click();const opened=await popup;await opened.close(); }
  await app.reload();await app.waitForSelector('.paper-card');
  await app.waitForFunction(()=>document.querySelectorAll('.paper-card').length===3);
  state=await api('GET_STATE');const finance=state.papers.find(p=>p.title.includes('evaluation'));
  await app.locator(`[data-paper="${finance.id}"] [data-exclude]`).click();
  await app.locator(`[data-paper="${finance.id}"].excluded`).waitFor();
  await app.getByRole('button',{name:/有笔记/}).click();assert.equal(await app.locator('.paper-card').count(),1);
  await app.getByRole('button',{name:/全部论文/}).click();await app.getByRole('searchbox',{name:'搜索论文'}).fill('evaluation');assert.equal(await app.locator('.paper-card').count(),1);
  await app.getByRole('searchbox',{name:'搜索论文'}).fill('');pass('Project list search and note/exclusion filters work');
  await app.locator(`[data-detail="${first.id}"]`).first().click();
  await app.getByRole('textbox',{name:'论文笔记',exact:true}).fill('<img src=x onerror=alert(1)> A note is text, not HTML.');
  await app.getByRole('button',{name:'保存笔记',exact:true}).click();
  await app.getByText('已保存',{exact:true}).waitFor();
  assert.equal(await app.locator('#drawer img').count(),0);
  await app.getByRole('button',{name:'删除笔记',exact:true}).click();await app.getByText('笔记已删除',{exact:true}).waitFor();
  await app.getByRole('textbox',{name:'论文笔记',exact:true}).fill('可用于文献综述的方法部分，之后再比较研究设计。');await app.getByRole('button',{name:'保存笔记',exact:true}).click();await app.getByText('已保存',{exact:true}).waitFor();
  await app.getByRole('button',{name:'关闭论文详情'}).click();pass('Detail note add/edit/delete works and arbitrary note HTML stays inert');
  // Exercise real background messages with a fake Zotero server. No personal account is used.
  await worker.evaluate(()=>{
    chrome.permissions.contains=async()=>true;
    globalThis.__zItems=[{key:'ABCD2345',version:1,data:{itemType:'journalArticle',title:'A practical guide to literature review methods',creators:[{creatorType:'author',firstName:'Robin',lastName:'Taylor'}],date:'2018'}}];
    globalThis.fetch=async(url,options={})=>{
      const headers={'Last-Modified-Version':'5','Total-Results':String(globalThis.__zItems.length)};
      if(globalThis.__zFail)return new Response('{}',{status:403});
      if(url.includes('/items/new'))return new Response(JSON.stringify({itemType:'journalArticle',tags:[]}));
      if(options.method==='POST') { const data=JSON.parse(options.body)[0],item={key:data.key,version:6,data};globalThis.__zItems.push(item);return new Response(JSON.stringify({successful:{0:item},failed:{}}),{headers}); }
      return new Response(JSON.stringify(globalThis.__zItems),{headers});
    };
  });
  await api('ZOTERO_CONNECT',{user_id:'123',api_key:'FakeTestingKey123456789'});
  state=await api('GET_STATE');assert.ok(state.zotero_links[first.id]);assert.equal(state.settings,undefined);assert.ok(!JSON.stringify(state).includes('FakeTestingKey'));
  await scholar.getByText('✓ 已存入 Zotero',{exact:true}).waitFor();pass('Zotero recognition appears on Scholar and secrets stay out of UI responses');
  await api('ZOTERO_ADD',{paper_id:finance.id});
  await api('ZOTERO_ADD',{paper_id:finance.id});
  assert.equal(await worker.evaluate(()=>globalThis.__zItems.length),2);pass('Confirmed Zotero write updates status and repeating save does not duplicate');
  await worker.evaluate(()=>{globalThis.__zFail=true;});
  const failed=await app.evaluate(()=>chrome.runtime.sendMessage({type:'ZOTERO_SYNC'}));assert.equal(failed.ok,false);
  state=await api('GET_STATE');assert.ok(state.zotero_links[first.id].stale);assert.ok(state.zotero_status.error);pass('Zotero failure preserves cached data and visibly marks it stale');
  await worker.evaluate(()=>{globalThis.__zFail=false;});await api('ZOTERO_SYNC');
  const exported=await api('EXPORT');assert.ok(!JSON.stringify(exported).includes('FakeTestingKey'));pass('Export excludes the Zotero API key');
  await api('PROJECT_ACTION',{action:'archive',project_id:projectB.id});await api('PROJECT_ACTION',{action:'restore',project_id:projectB.id});
  await api('PROJECT_ACTION',{action:'delete',project_id:projectB.id});assert.equal((await api('GET_STATE')).projects.length,1);pass('Archive/restore/delete leave other project data intact');
  const concurrent=await api('CREATE_PROJECT',{name:'Concurrency test'});
  await Promise.all(Array.from({length:20},(_,i)=>api('RECORD_CLICK',{project_id:concurrent.id,paper:{title:`Concurrent title ${i}`,authors:'J Smith',year:'2024',external_ids:[`scholar:cid:c${i}`]},context:{search_query:'concurrent'}})));
  assert.equal((await api('GET_STATE')).project_papers.filter(p=>p.project_id===concurrent.id).length,20);pass('Concurrent tab writes do not drop research history');
  await api('PROJECT_ACTION',{action:'delete',project_id:concurrent.id});await api('PROJECT_ACTION',{action:'switch',project_id:projectA});
  await app.reload();await app.waitForSelector('.paper-card');
  await app.screenshot({path:path.join(out,'project.png'),fullPage:true});
  await scholar.reload();await scholar.locator('.scholartrail-excluded').waitFor();await scholar.screenshot({path:path.join(out,'scholar.png'),fullPage:true});
  const popup=await context.newPage();await popup.goto(`chrome-extension://${id}/popup.html`);await popup.getByRole('button',{name:'打开项目'}).waitFor();await popup.setViewportSize({width:340,height:420});await popup.screenshot({path:path.join(out,'popup.png')});
  await app.locator(`[data-detail="${first.id}"]`).first().click();await app.waitForSelector('.timeline-item');await app.screenshot({path:path.join(out,'note-history.png'),fullPage:true});await app.getByRole('button',{name:'关闭论文详情'}).click();
  await app.goto(`chrome-extension://${id}/app.html#settings`);await app.getByRole('heading',{name:'设置与连接'}).waitFor();
  await app.screenshot({path:path.join(out,'settings.png'),fullPage:true});
  await app.goto(`chrome-extension://${id}/app.html`);await app.waitForSelector('.paper-card');await app.locator('#new-project').click();await app.locator('#project-dialog[open]').waitFor();
  await app.screenshot({path:path.join(out,'create-project.png'),fullPage:true});await app.locator('#cancel-dialog').click();
  assert.deepEqual(errors,[]);pass('No page runtime errors in extension screens or injected UI');
  await context.close();context=await chromium.launchPersistentContext(path.join(out,'profile'),options);
  const reopened=await context.newPage();await reopened.goto(`chrome-extension://${id}/app.html`);await reopened.waitForSelector('.paper-card');assert.equal(await reopened.locator('.paper-card').count(),3);pass('Browser restart preserves projects, notes, decisions and history');
  await writeFile(path.join(out,'results.json'),JSON.stringify({checks,errors,fixture:'Representative Google Scholar DOM; mocked Zotero API; real Chromium extension lifecycle'},null,2));
} finally { await context.close(); }
